# Generated by Django 6.0.3 on 2026-05-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_direct',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_public',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('PUBLIC', 'Public Channel'), ('DIRECT', 'Direct Message'), ('GROUP', 'Private Group')], default='DIRECT', max_length=10),
        ),
    ]
