# Generated by Django 6.0.3 on 2026-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
